version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.16
    container_name: wakedock-vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    networks:
      - wakedock-network
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root-token
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    command: ["vault", "server", "-dev", "-dev-listen-address=0.0.0.0:8200"]
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/data
      - vault-logs:/vault/logs
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  vault-data:
  vault-logs:

networks:
  wakedock-network:
    external: true