# Development override for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  wakedock:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    environment:
      - WAKEDOCK_DEBUG=true
      - WAKEDOCK_LOG_LEVEL=DEBUG
      - WAKEDOCK_RELOAD=true
    ports:
      - "8000:8000"
      - "5678:5678" # Debugger port

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.dev
    volumes:
      - ./dashboard/src:/app/src
      - ./dashboard/static:/app/static
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "24678:24678" # HMR port

  caddy:
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
