services:
  wordpress:
    image: wordpress:latest
    container_name: wakedock-wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress-db
    networks:
      - wakedock-network

  wordpress-db:
    image: mysql:5.7
    container_name: wakedock-wordpress-db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - wakedock-network

volumes:
  wordpress_data:
  wordpress_db:


networks:
  wakedock-network:
    external: true
