---
# Common role for basic server setup
- name: Set timezone
  timezone:
    name: "{{ system_timezone | default('UTC') }}"

- name: Set locale
  locale_gen:
    name: "{{ system_locale | default('en_US.UTF-8') }}"
    state: present

- name: Update package cache
  package:
    update_cache: yes
  when: system_update_cache | default(true)

- name: Install essential packages
  package:
    name:
      - curl
      - wget
      - git
      - unzip
      - htop
      - vim
      - net-tools
      - rsync
      - cron
    state: present

- name: Create wakedock user
  user:
    name: "{{ wakedock_user | default('wakedock') }}"
    group: "{{ wakedock_group | default('wakedock') }}"
    home: "{{ wakedock_home | default('/opt/wakedock') }}"
    shell: /bin/bash
    system: yes
    create_home: yes

- name: Create wakedock directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ wakedock_user | default('wakedock') }}"
    group: "{{ wakedock_group | default('wakedock') }}"
    mode: '0755'
  loop:
    - "{{ wakedock_home | default('/opt/wakedock') }}"
    - "{{ docker_data_dir | default('/opt/wakedock/data') }}"
    - "{{ docker_logs_dir | default('/opt/wakedock/logs') }}"
    - "{{ docker_config_dir | default('/opt/wakedock/config') }}"

- name: Configure sudo for wakedock user
  lineinfile:
    path: /etc/sudoers.d/wakedock
    create: yes
    line: "{{ wakedock_user | default('wakedock') }} ALL=(ALL) NOPASSWD: /usr/bin/docker, /usr/local/bin/docker-compose"
    mode: '0440'

- name: Setup log rotation
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/wakedock
    mode: '0644'
