# WakeDock Logging Configuration

version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s:%(funcName)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  json:
    format: "%(asctime)s"
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    datefmt: "%Y-%m-%d %H:%M:%S"

filters:
  sensitive_data:
    (): wakedock.log_config.SensitiveDataFilter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
    filters: [sensitive_data]
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/wakedock.log
    maxBytes: 104857600  # 100MB
    backupCount: 5
    encoding: utf8
    filters: [sensitive_data]
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/wakedock-error.log
    maxBytes: 104857600  # 100MB
    backupCount: 5
    encoding: utf8
    filters: [sensitive_data]
  
  access_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: logs/wakedock-access.log
    maxBytes: 104857600  # 100MB
    backupCount: 10
    encoding: utf8

loggers:
  wakedock:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: false
  
  wakedock.api:
    level: INFO
    handlers: [console, file, access_file]
    propagate: false
  
  wakedock.core:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  wakedock.database:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  wakedock.security:
    level: WARNING
    handlers: [console, file, error_file]
    propagate: false
  
  uvicorn:
    level: INFO
    handlers: [console, access_file]
    propagate: false
  
  uvicorn.access:
    level: INFO
    handlers: [access_file]
    propagate: false
  
  uvicorn.error:
    level: WARNING
    handlers: [console, error_file]
    propagate: false
  
  sqlalchemy:
    level: WARNING
    handlers: [console, file]
    propagate: false
  
  sqlalchemy.engine:
    level: INFO
    handlers: [file]
    propagate: false
  
  alembic:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  docker:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  httpx:
    level: WARNING
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console, file]
