# WakeDock Secrets Configuration
# This file defines how secrets are managed in different environments

# Development - Use environment variables or .env file
# Production - Use Docker secrets or Kubernetes secrets

# Example Docker Compose with secrets
version: '3.8'

services:
  wakedock:
    image: wakedock:latest
    secrets:
      - wakedock_api_key
      - wakedock_jwt_secret
      - wakedock_encryption_key
      - wakedock_csrf_secret
      - wakedock_database_url
    environment:
      - WAKEDOCK_API_KEY_FILE=/run/secrets/wakedock_api_key
      - WAKEDOCK_JWT_SECRET_FILE=/run/secrets/wakedock_jwt_secret
      - WAKEDOCK_ENCRYPTION_KEY_FILE=/run/secrets/wakedock_encryption_key
      - WAKEDOCK_CSRF_SECRET_FILE=/run/secrets/wakedock_csrf_secret
      - WAKEDOCK_DATABASE_URL_FILE=/run/secrets/wakedock_database_url

secrets:
  wakedock_api_key:
    file: ./secrets/api_key.txt
  wakedock_jwt_secret:
    file: ./secrets/jwt_secret.txt
  wakedock_encryption_key:
    file: ./secrets/encryption_key.txt
  wakedock_csrf_secret:
    file: ./secrets/csrf_secret.txt
  wakedock_database_url:
    file: ./secrets/database_url.txt

# Alternative: External secrets (recommended for production)
# secrets:
#   wakedock_api_key:
#     external: true
#     name: wakedock_api_key_v1
#   wakedock_jwt_secret:
#     external: true
#     name: wakedock_jwt_secret_v1
