---
# Security hardening role
- name: Configure firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ allowed_ports }}"
  when: firewall_enabled | default(true)

- name: Enable UFW firewall
  ufw:
    state: enabled
    policy: deny
  when: firewall_enabled | default(true)

- name: Disable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: restart ssh

- name: Configure SSH to use only strong ciphers
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      # Security hardening
      Protocol 2
      PermitRootLogin no
      MaxAuthTries 3
      ClientAliveInterval 300
      ClientAliveCountMax 2
      Ciphers aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr
      MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
      KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group16-sha512
    marker: "# {mark} ANSIBLE MANAGED BLOCK - SSH Security"
  notify: restart ssh

- name: Install fail2ban
  package:
    name: fail2ban
    state: present

- name: Configure fail2ban for SSH
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: '0644'
  notify: restart fail2ban

- name: Start and enable fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes

- name: Set secure permissions on sensitive files
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "/etc/shadow", mode: "0640" }
    - { path: "/etc/gshadow", mode: "0640" }
    - { path: "/etc/passwd", mode: "0644" }
    - { path: "/etc/group", mode: "0644" }

- name: Configure automatic security updates
  package:
    name: unattended-upgrades
    state: present

- name: Configure unattended-upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: '0644'
