apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    version: 1
    basicAuth: false
    jsonData:
      httpMethod: GET
      queryTimeout: 60s
      timeInterval: 30s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
    secureJsonData: {}

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    version: 1
    basicAuth: false
    jsonData:
      httpMethod: GET
      maxLines: 1000
